window.HISTORICAL_PROJECTS = Object.freeze([
  {
    id: 'parque-arauco-boulevard',
    titulo: 'Parque Arauco Boulevard',
    anio: null,
    cliente: 'Massiva',
    ubicacion: 'Santiago',
    categoria: 'Centro comercial',
    imagen: '../images/Mall Parque Arauco  -- Diseñada para Massiva - Restaurantes y Boulevard --  110m2.jpg',
    descripcion: 'Integración de una pantalla LED en un entorno comercial de alta circulación y operación continua.',
  },
  {
    id: 'metro-tobalaba',
    titulo: 'Metro Tobalaba',
    anio: null,
    cliente: 'Massiva',
    ubicacion: 'Santiago',
    categoria: 'Metro',
    imagen: '../images/Metro Tobalaba -- Diseñado para Massiva -  Mega Led curva anden - 73m2.jpg',
    descripcion: 'Pantalla curva desarrollada para un andén con alto flujo de pasajeros y restricciones precisas de montaje.',
  },
  {
    id: 'aeropuerto-santiago-mega-led',
    titulo: 'Mega LED Aeropuerto de Santiago',
    anio: null,
    cliente: 'Massiva',
    ubicacion: 'Pudahuel, Santiago',
    categoria: 'Aeropuerto',
    imagen: '../images/Aeropuerto -- Diseñado para Massiva -  Mega Led - 2x 63m22.jpg',
    descripcion: 'Soporte publicitario integrado a un recinto operativo, con foco en seguridad y continuidad.',
  },
  {
    id: 'aeropuerto-santiago-transparentes',
    titulo: 'Pantallas transparentes y teleindicador',
    anio: null,
    cliente: 'Massiva',
    ubicacion: 'Aeropuerto de Santiago',
    categoria: 'Aeropuerto',
    imagen: '../images/Aeropuerto -- Diseñado para Massiva -  6 pantallas  Led transparentes y Teleindicador - 6 x13m2.jpg',
    descripcion: 'Sistema de pantallas transparentes coordinado con la arquitectura y circulación del terminal.',
  },
  {
    id: 'mall-plaza-vespucio-froilan-roa',
    titulo: 'Fachada Froilán Roa',
    anio: null,
    cliente: 'Global',
    ubicacion: 'Mall Plaza Vespucio, Santiago',
    categoria: 'Centro comercial',
    imagen: '../images/Mall Plaza Vespucio - Diseñada para Global - Fachada Froilan Roa remodelada ......    230m2.jpg',
    descripcion: 'Pantalla de gran formato integrada a una fachada comercial y a su operación cotidiana.',
  },
  {
    id: 'mall-plaza-vespucio-3d',
    titulo: 'Pantalla 3D Boulevard',
    anio: null,
    cliente: 'Clear Channel',
    ubicacion: 'Mall Plaza Vespucio, Santiago',
    categoria: 'Centro comercial',
    imagen: '../images/Mall Plaza Vespucio - Diseñada para Clear Channel -   3D Boulevard -- 89m2.jpg',
    descripcion: 'Solución estructural para una pantalla 3D en un boulevard comercial de alta visibilidad.',
  },
  {
    id: 'mall-plaza-egana',
    titulo: 'Pantalla interior Mall Plaza Egaña',
    anio: null,
    cliente: 'Clear Channel',
    ubicacion: 'La Reina, Santiago',
    categoria: 'Centro comercial',
    imagen: '../images/Mall Plaza Egaña  -- Diseñado para Clear Channel - interior tiendas  -- 15m2.jpg',
    descripcion: 'Pantalla integrada a un contexto interior donde arquitectura, visibilidad y estructura responden como un sistema.',
  },
  {
    id: 'padre-hurtado-bilbao',
    titulo: 'Padre Hurtado con Bilbao',
    anio: null,
    cliente: 'Global',
    ubicacion: 'La Reina, Santiago',
    categoria: 'Vía pública',
    imagen: '../images/Via Pública --Diseñada para Global --  Padre Hurtado  Bilbao--  - Sector Mall  Portal La Reina--  2x15m2.jpg',
    descripcion: 'Estructura exterior concebida para condiciones reales de viento, visibilidad y montaje urbano.',
  },
  {
    id: 'mall-plaza-el-trebol',
    titulo: 'Exterior Mall Plaza El Trébol',
    anio: null,
    cliente: 'Clear Channel',
    ubicacion: 'Concepción',
    categoria: 'Vía pública',
    imagen: '../images/Via Pública -- Diseñada para Clear Channel --Exterior Mall Plaza El Trebol Concepcion --  -  40m2.jpg',
    descripcion: 'Proyecto de borde comercial coordinado con la fachada y la operación del recinto.',
  },
  {
    id: 'rotonda-tomas-moro',
    titulo: 'Rotonda Tomás Moro',
    anio: null,
    cliente: 'JCDecaux',
    ubicacion: 'Las Condes, Santiago',
    categoria: 'Vía pública',
    imagen: '../images/Via Pública -- Diseñada para  JC Decaux -- Rotonda Tomas Moro-- Diseñada pa JC Decaux - -  15m2.jpg',
    descripcion: 'Soporte urbano donde orientación, seguridad y montaje condicionan cada decisión.',
  },
  {
    id: 'metro-plaza-egana',
    titulo: 'Metro Plaza Egaña',
    anio: null,
    cliente: 'Massiva',
    ubicacion: 'La Reina, Santiago',
    categoria: 'Metro',
    imagen: '../images/Metro Plaza Egaña  -- Diseñado para Massiva - - 2x 17m2.jpg',
    descripcion: 'Solución LED para un punto de alta circulación, diseñada para instalarse y operar con control técnico.',
  },
  {
    id: 'metro-los-leones',
    titulo: 'Túnel LED Metro Los Leones',
    anio: null,
    cliente: 'Massiva',
    ubicacion: 'Providencia, Santiago',
    categoria: 'Metro',
    imagen: '../images/Metro Los Leones -- Diseñado para Massiva -  Tunel Led - 2x 17m2.jpg',
    descripcion: 'Pantallas para un túnel de conexión, ajustadas a las condiciones de la infraestructura existente.',
  },
  {
    id: 'estadio-la-serena',
    titulo: 'Estadio La Serena',
    anio: null,
    cliente: 'LED Studio',
    ubicacion: 'La Serena',
    categoria: 'Estadio',
    imagen: '../images/Estadio La Serena -- Diseñado para Led Studio - 33m2.jpg',
    descripcion: 'Estructura para una pantalla LED expuesta a público, eventos y exigencias de continuidad.',
  },
  {
    id: 'estadio-sausalito',
    titulo: 'Estadio Sausalito',
    anio: null,
    cliente: 'LED Studio',
    ubicacion: 'Viña del Mar',
    categoria: 'Estadio',
    imagen: '../images/Estadio Sausalito -- Diseñado para Led Studio -   -- 71m2.jpg',
    descripcion: 'Proyecto para operación durante eventos, donde visibilidad, seguridad y confiabilidad son inseparables.',
  },
  {
    id: 'camion-led',
    titulo: 'Camión LED',
    anio: null,
    cliente: 'City Projects',
    ubicacion: 'Chile',
    categoria: 'Móvil',
    imagen: '../images/Movil - Camion Led  -- Diseñado para City Proyects - 18m2.jpg',
    descripcion: 'Soporte móvil para pantalla LED diseñado para trasladar presencia publicitaria a distintos puntos.',
  },
])
